networks:
  laravel_network:

volumes:
  mysql_data:  
    driver: local
services:
  server:
    build:
      context: .
      dockerfile: docker/dockerfiles/nginx.dockerfile
    container_name: laravel_server
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel_network

  php:
    build:
      context: .
      dockerfile: docker/dockerfiles/php.dockerfile
    container_name: laravel_php
    volumes:
      - ./backend:/var/www/html
    environment:
      - PHP_FPM_USER=laravel
      - PHP_FPM_GROUP=laravel
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0.42
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root.pa55
      MYSQL_DATABASE: laravel_project
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1.pa55
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel_network
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel_phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root.pa55
    networks:
      - laravel_network

  composer:
    build:
      context: .
      dockerfile: docker/dockerfiles/composer.dockerfile
    depends_on:
      - php
    volumes:
      - ./backend:/var/www/html:delegated
    networks:
      - laravel_network

  artisan:
    build:
      context: .
      dockerfile: docker/dockerfiles/php.dockerfile
    entrypoint: ["php", "/var/www/html/artisan"]
    volumes:
      - ./backend:/var/www/html:delegated
    networks:
      - laravel_network