networks:
  laravel_network:


services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: laravel_server
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel_network

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: laravel_php
    volumes:
      - ./src:/var/www/html
    environment:
      - PHP_FPM_USER=laravel
      - PHP_FPM_GROUP=laravel
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0.42
    container_name: laravel_mysql
    restart: unless-stopped
    env_file:
      - mysql/.env
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel_phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root.pa55
    networks:
      - laravel_network

  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer.dockerfile
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel_network

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    entrypoint: [ "php", "/var/www/html/artisan" ]
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel_network
